#include <iostream.h>
#include <conio.h>

int main ();
{
   structsegitiga;
{
float keliling;
float luas;
};
segitiga alas, tinggi, miring, x;
cout<<"-------------------------------------------------------------"<<endl;
cout<<"            Menghitung LUAS dan KELILING SEGITIGA            "<<endl;
cout<<"-------------------------------------------------------------"<<endl;
cout<<"\t ===         ANANDA PUTRI SYAVIRA                  === \n\n";
cout<<"\t ===           130533608243                        ===\n\n";
cout<<"\t ===            PTI'13 OFF B                       ===\n\n";
cout<<"\t ===------------------**---------------------------===\n\n";
cout<<"keterang : "endl;
cout<<" a= sisi alas segitiga "<<endl;
cout<<" b= sisi tinggi segitiga "<<endl;
cout<<" c= sisi miring segitiga "<<endl;
cou<<"a = ";
cin>>alas.luas;
cout<<" b = ";
cin>>tinggi.luas;
cout<<" c= ";
cin>>miring.luas;
cout<<endl;
x.luas=(alas.luas*tinggi.luas)/2;
x.keliling=alas.luas=tinggi.luas+miring.luas;
cout<<"luassegitiga = "<<x.luas<<" cm " <<endl;
cout<<"KelilingSegitiga = "<<x.keliling<<"cm "<<endl<<endl;
getch();
}

